import { GateDefinition, GateType, SignalValue } from './types';

export const GATE_DEFINITIONS: Record<GateType, GateDefinition> = {
  AND: {
    type: 'AND',
    label: 'AND',
    description: 'Output is 1 only when all inputs are 1',
    inputs: 2,
    outputs: 1,
    isSource: false,
    isSink: false,
    category: 'gate',
    evaluate: (i: SignalValue[]): SignalValue => (i[0] === 1 && i[1] === 1 ? 1 : 0),
  },
  OR: {
    type: 'OR',
    label: 'OR',
    description: 'Output is 1 when at least one input is 1',
    inputs: 2,
    outputs: 1,
    isSource: false,
    isSink: false,
    category: 'gate',
    evaluate: (i: SignalValue[]): SignalValue => (i[0] === 1 || i[1] === 1 ? 1 : 0),
  },
  NOT: {
    type: 'NOT',
    label: 'NOT',
    description: 'Output is the inverse of the input',
    inputs: 1,
    outputs: 1,
    isSource: false,
    isSink: false,
    category: 'gate',
    evaluate: (i: SignalValue[]): SignalValue => (i[0] === 1 ? 0 : 1),
  },
  NAND: {
    type: 'NAND',
    label: 'NAND',
    description: 'AND followed by NOT — output is 0 only when all inputs are 1',
    inputs: 2,
    outputs: 1,
    isSource: false,
    isSink: false,
    category: 'gate',
    evaluate: (i: SignalValue[]): SignalValue => (i[0] === 1 && i[1] === 1 ? 0 : 1),
  },
  NOR: {
    type: 'NOR',
    label: 'NOR',
    description: 'OR followed by NOT — output is 1 only when all inputs are 0',
    inputs: 2,
    outputs: 1,
    isSource: false,
    isSink: false,
    category: 'gate',
    evaluate: (i: SignalValue[]): SignalValue => (i[0] === 1 || i[1] === 1 ? 0 : 1),
  },
  XOR: {
    type: 'XOR',
    label: 'XOR',
    description: 'Exclusive OR — output is 1 when inputs differ',
    inputs: 2,
    outputs: 1,
    isSource: false,
    isSink: false,
    category: 'gate',
    evaluate: (i: SignalValue[]): SignalValue => (i[0] !== i[1] ? 1 : 0),
  },
  XNOR: {
    type: 'XNOR',
    label: 'XNOR',
    description: 'Exclusive NOR — output is 1 when inputs are the same',
    inputs: 2,
    outputs: 1,
    isSource: false,
    isSink: false,
    category: 'gate',
    evaluate: (i: SignalValue[]): SignalValue => (i[0] === i[1] ? 1 : 0),
  },
  INPUT: {
    type: 'INPUT',
    label: 'Input',
    description: 'User-controlled input switch — click to toggle',
    inputs: 0,
    outputs: 1,
    isSource: true,
    isSink: false,
    category: 'input',
    evaluate: (i: SignalValue[]): SignalValue => (i.length > 0 ? i[0] : 0),
  },
  OUTPUT: {
    type: 'OUTPUT',
    label: 'Output',
    description: 'LED display — lights up when signal is 1',
    inputs: 1,
    outputs: 0,
    isSource: false,
    isSink: true,
    category: 'output',
    evaluate: (i: SignalValue[]): SignalValue => (i.length > 0 ? i[0] : 0),
  },
  HIGH: {
    type: 'HIGH',
    label: 'High (1)',
    description: 'Constant logical 1',
    inputs: 0,
    outputs: 1,
    isSource: true,
    isSink: false,
    category: 'input',
    evaluate: (): SignalValue => 1,
  },
  LOW: {
    type: 'LOW',
    label: 'Low (0)',
    description: 'Constant logical 0',
    inputs: 0,
    outputs: 1,
    isSource: true,
    isSink: false,
    category: 'input',
    evaluate: (): SignalValue => 0,
  },
  CLOCK: {
    type: 'CLOCK',
    label: 'Clock',
    description: 'Auto-toggling clock signal',
    inputs: 0,
    outputs: 1,
    isSource: true,
    isSink: false,
    category: 'input',
    evaluate: (i: SignalValue[]): SignalValue => (i.length > 0 ? i[0] : 0),
  },
};

export const PALETTE_ORDER: GateType[] = [
  'INPUT',
  'HIGH',
  'LOW',
  'CLOCK',
  'OUTPUT',
  'AND',
  'OR',
  'NOT',
  'NAND',
  'NOR',
  'XOR',
  'XNOR',
];

/** Standard gate dimensions in canvas units. */
export const GATE_WIDTH = 80;
export const GATE_HEIGHT = 60;
