// All notes content for the Notes tab.
// Structured for easy rendering in the NotesPanel component.

export interface NoteSection {
  id: string;
  title: string;
  icon: string; // emoji or short text
  intro?: string;
  blocks: NoteBlock[];
}

export type NoteBlock =
  | { type: 'paragraph'; text: string }
  | { type: 'heading'; text: string }
  | { type: 'list'; items: string[] }
  | { type: 'table'; headers: string[]; rows: string[][] }
  | { type: 'example'; title: string; expression: string; explanation: string }
  | { type: 'tip'; text: string }
  | { type: 'warning'; text: string };

export const GATE_NOTES: NoteSection[] = [
  {
    id: 'gates-intro',
    title: 'Logic Gates — The Complete Reference',
    icon: '⚡',
    intro: 'Logic gates are the building blocks of every digital circuit. Each gate takes one or more binary inputs (0 or 1) and produces a single binary output. Below you will find every standard gate, its symbol, its truth table for 2 inputs, and a short explanation.',
    blocks: [
      { type: 'heading', text: 'What is a logic gate?' },
      { type: 'paragraph', text: 'A logic gate is an electronic switch that performs a boolean function on one or more binary inputs to produce a single binary output. The two binary digits are 0 (LOW / FALSE / OFF) and 1 (HIGH / TRUE / ON). Gates are implemented using transistors and form the basis of every microprocessor, memory chip, and digital system ever built.' },
      { type: 'heading', text: 'The 7 basic gates' },
      { type: 'list', items: [
        'AND — output is 1 only if ALL inputs are 1',
        'OR — output is 1 if AT LEAST ONE input is 1',
        'NOT — output is the opposite of the input (also called an inverter)',
        'NAND — AND followed by NOT (a "universal" gate)',
        'NOR — OR followed by NOT (also "universal")',
        'XOR — Exclusive OR: output is 1 when inputs DIFFER',
        'XNOR — Exclusive NOR: output is 1 when inputs are THE SAME',
      ] },
      { type: 'tip', text: 'NAND and NOR are called "universal gates" because any other gate (AND, OR, NOT, even XOR) can be built using only NANDs or only NORs. This is why real chips are often built entirely from NAND gates.' },
    ],
  },
  {
    id: 'gate-and',
    title: 'AND Gate',
    icon: '∧',
    intro: 'Output is 1 only when every input is 1. Think of it as a series circuit — both switches must be closed.',
    blocks: [
      { type: 'paragraph', text: 'The AND gate is the logical equivalent of multiplication. If any single input is 0, the output is forced to 0. Boolean expression: F = A · B (or A AND B, or A ∧ B, or simply AB).' },
      { type: 'heading', text: '2-input truth table' },
      { type: 'table', headers: ['A', 'B', 'F = A·B'], rows: [
        ['0','0','0'],
        ['0','1','0'],
        ['1','0','0'],
        ['1','1','1'],
      ] },
      { type: 'heading', text: '3-input truth table' },
      { type: 'table', headers: ['A','B','C','F = A·B·C'], rows: [
        ['0','0','0','0'],
        ['0','0','1','0'],
        ['0','1','0','0'],
        ['0','1','1','0'],
        ['1','0','0','0'],
        ['1','0','1','0'],
        ['1','1','0','0'],
        ['1','1','1','1'],
      ] },
      { type: 'heading', text: '4-input truth table (sample rows)' },
      { type: 'paragraph', text: 'A 4-input AND has 16 rows; only the row A=B=C=D=1 gives F=1. All other 15 combinations produce F=0. The full expression is F = A·B·C·D.' },
      { type: 'tip', text: 'Real-world example: a seat-belt alarm. The buzzer sounds only if (key is ON) AND (seat occupied) AND (belt unbuckled). All three conditions must be true.' },
    ],
  },
  {
    id: 'gate-or',
    title: 'OR Gate',
    icon: '∨',
    intro: 'Output is 1 if at least one input is 1. Think of it as a parallel circuit — either switch being closed is enough.',
    blocks: [
      { type: 'paragraph', text: 'The OR gate is the logical equivalent of addition. The only way to get a 0 is if every input is 0. Boolean expression: F = A + B (also written A ∨ B or A OR B).' },
      { type: 'heading', text: '2-input truth table' },
      { type: 'table', headers: ['A','B','F = A+B'], rows: [
        ['0','0','0'],
        ['0','1','1'],
        ['1','0','1'],
        ['1','1','1'],
      ] },
      { type: 'heading', text: '3-input truth table' },
      { type: 'table', headers: ['A','B','C','F = A+B+C'], rows: [
        ['0','0','0','0'],
        ['0','0','1','1'],
        ['0','1','0','1'],
        ['0','1','1','1'],
        ['1','0','0','1'],
        ['1','0','1','1'],
        ['1','1','0','1'],
        ['1','1','1','1'],
      ] },
      { type: 'heading', text: '4-input truth table' },
      { type: 'paragraph', text: 'A 4-input OR has 16 rows; only A=B=C=D=0 gives F=0. Every other row produces F=1. The full expression is F = A + B + C + D.' },
      { type: 'tip', text: 'Real-world example: a fire alarm. The alarm rings if (smoke detected) OR (heat detected) OR (manual pull). Any single trigger is enough.' },
    ],
  },
  {
    id: 'gate-not',
    title: 'NOT Gate (Inverter)',
    icon: '¬',
    intro: 'Output is the opposite of the input. A single-input gate.',
    blocks: [
      { type: 'paragraph', text: 'The NOT gate flips the bit: 0 becomes 1 and 1 becomes 0. Boolean expression: F = Ā (read as "A bar") or F = ¬A or F = !A or F = A\'.' },
      { type: 'heading', text: 'Truth table' },
      { type: 'table', headers: ['A','F = Ā'], rows: [
        ['0','1'],
        ['1','0'],
      ] },
      { type: 'tip', text: 'NOT is the only single-input standard gate. Combining NOT with AND gives NAND; combining NOT with OR gives NOR.' },
    ],
  },
  {
    id: 'gate-nand',
    title: 'NAND Gate',
    icon: '⊼',
    intro: 'AND followed by NOT. Output is 0 only when ALL inputs are 1. Universal gate.',
    blocks: [
      { type: 'paragraph', text: 'NAND = NOT(AND). Boolean expression: F = (A·B)̄ or F = A ↑ B.' },
      { type: 'heading', text: '2-input truth table' },
      { type: 'table', headers: ['A','B','F = (A·B)̄'], rows: [
        ['0','0','1'],
        ['0','1','1'],
        ['1','0','1'],
        ['1','1','0'],
      ] },
      { type: 'heading', text: '3-input truth table' },
      { type: 'table', headers: ['A','B','C','F = (A·B·C)̄'], rows: [
        ['0','0','0','1'],
        ['0','0','1','1'],
        ['0','1','0','1'],
        ['0','1','1','1'],
        ['1','0','0','1'],
        ['1','0','1','1'],
        ['1','1','0','1'],
        ['1','1','1','0'],
      ] },
      { type: 'tip', text: 'NAND is the most popular gate in real chips because CMOS NAND is slightly faster and uses fewer transistors than NOR.' },
    ],
  },
  {
    id: 'gate-nor',
    title: 'NOR Gate',
    icon: '⊽',
    intro: 'OR followed by NOT. Output is 1 only when ALL inputs are 0. Universal gate.',
    blocks: [
      { type: 'paragraph', text: 'NOR = NOT(OR). Boolean expression: F = (A+B)̄ or F = A ↓ B.' },
      { type: 'heading', text: '2-input truth table' },
      { type: 'table', headers: ['A','B','F = (A+B)̄'], rows: [
        ['0','0','1'],
        ['0','1','0'],
        ['1','0','0'],
        ['1','1','0'],
      ] },
      { type: 'heading', text: '3-input truth table' },
      { type: 'table', headers: ['A','B','C','F = (A+B+C)̄'], rows: [
        ['0','0','0','1'],
        ['0','0','1','0'],
        ['0','1','0','0'],
        ['0','1','1','0'],
        ['1','0','0','0'],
        ['1','0','1','0'],
        ['1','1','0','0'],
        ['1','1','1','0'],
      ] },
    ],
  },
  {
    id: 'gate-xor',
    title: 'XOR Gate (Exclusive OR)',
    icon: '⊕',
    intro: 'Output is 1 when inputs DIFFER. Used in adders, parity checks, and cryptography.',
    blocks: [
      { type: 'paragraph', text: 'XOR outputs 1 if and only if an ODD number of inputs are 1. For 2 inputs, that means "different". Boolean expression: F = A ⊕ B = A·B̄ + Ā·B.' },
      { type: 'heading', text: '2-input truth table' },
      { type: 'table', headers: ['A','B','F = A ⊕ B'], rows: [
        ['0','0','0'],
        ['0','1','1'],
        ['1','0','1'],
        ['1','1','0'],
      ] },
      { type: 'heading', text: '3-input truth table' },
      { type: 'table', headers: ['A','B','C','F = A ⊕ B ⊕ C'], rows: [
        ['0','0','0','0'],
        ['0','0','1','1'],
        ['0','1','0','1'],
        ['0','1','1','0'],
        ['1','0','0','1'],
        ['1','0','1','0'],
        ['1','1','0','0'],
        ['1','1','1','1'],
      ] },
      { type: 'tip', text: 'Note: 3-input XOR is NOT "exactly one input is 1" — it is "odd number of inputs are 1". So A=B=C=1 gives F=1.' },
      { type: 'example', title: 'Real use', expression: 'A ⊕ A = 0', explanation: 'XOR-ing a value with itself always gives 0. This is used in cryptography and to zero registers in CPUs.' },
    ],
  },
  {
    id: 'gate-xnor',
    title: 'XNOR Gate (Exclusive NOR)',
    icon: '⊙',
    intro: 'Output is 1 when inputs are EQUAL. The complement of XOR.',
    blocks: [
      { type: 'paragraph', text: 'XNOR outputs 1 if an EVEN number of inputs are 1 (including zero). For 2 inputs, this means "the same". Boolean expression: F = A ⊙ B = A·B + Ā·B̄.' },
      { type: 'heading', text: '2-input truth table' },
      { type: 'table', headers: ['A','B','F = A ⊙ B'], rows: [
        ['0','0','1'],
        ['0','1','0'],
        ['1','0','0'],
        ['1','1','1'],
      ] },
      { type: 'heading', text: '3-input truth table' },
      { type: 'table', headers: ['A','B','C','F = A ⊙ B ⊙ C'], rows: [
        ['0','0','0','1'],
        ['0','0','1','0'],
        ['0','1','0','0'],
        ['0','1','1','1'],
        ['1','0','0','0'],
        ['1','0','1','1'],
        ['1','1','0','1'],
        ['1','1','1','0'],
      ] },
      { type: 'tip', text: 'XNOR is also called the "equivalence gate" because it outputs 1 when all inputs are equal.' },
    ],
  },
  {
    id: 'gate-summary',
    title: 'Quick Reference: All Gates at a Glance',
    icon: '📋',
    intro: 'Use this as a cheat sheet for exams and circuit design.',
    blocks: [
      { type: 'table', headers: ['Gate','Inputs','Symbol','Boolean Expression','Output is 1 when…'], rows: [
        ['AND','2','∧','A·B','both inputs are 1'],
        ['OR','2','∨','A+B','any input is 1'],
        ['NOT','1','¬','Ā','input is 0'],
        ['NAND','2','⊼','(A·B)̄','NOT both inputs are 1'],
        ['NOR','2','⊽','(A+B)̄','both inputs are 0'],
        ['XOR','2','⊕','A⊕B','inputs differ'],
        ['XNOR','2','⊙','A⊙B','inputs are equal'],
      ] },
      { type: 'warning', text: 'For 3+ input XOR/XNOR, remember: XOR = odd parity, XNOR = even parity. NOT "exactly one input is 1".' },
    ],
  },
];

export const KMAP_NOTES: NoteSection[] = [
  {
    id: 'kmap-intro',
    title: 'Karnaugh Maps — A Beginner-Friendly Guide',
    icon: '🗺️',
    intro: 'A Karnaugh map (K-map) is a visual method for simplifying boolean expressions without using algebra. It was invented by Maurice Karnaugh in 1953 and is still taught because it builds intuition that algebra-only methods lack.',
    blocks: [
      { type: 'heading', text: 'Why use a K-map?' },
      { type: 'paragraph', text: 'Boolean expressions can often be simplified. For example, A·B + A·B·C can be reduced to just A·B (using the absorption law). Doing this with algebra requires spotting the right law to apply at each step. A K-map lets you SEE the simplification by laying out the truth table in a special grid where adjacent cells differ by only one variable.' },
      { type: 'heading', text: 'The big idea' },
      { type: 'paragraph', text: 'In a K-map, every cell represents one row of the truth table (one minterm). Cells are arranged so that moving one step in any direction changes exactly ONE variable. This means any two adjacent cells that both contain 1 can be combined into a single term — the differing variable drops out.' },
      { type: 'tip', text: 'Maurice Karnaugh was an engineer at Bell Labs. His map is a refinement of the earlier Veitch diagram, which itself came from work by Edward W. Veitch and Allan Marquand in the 1950s.' },
    ],
  },
  {
    id: 'kmap-how-to-build',
    title: 'How to Draw a K-map (2, 3, 4 variables)',
    icon: '✏️',
    blocks: [
      { type: 'heading', text: 'Step 1: Count variables, choose grid size' },
      { type: 'list', items: [
        '2 variables (A, B) → 2×2 grid (4 cells = 2² minterms)',
        '3 variables (A, B, C) → 2×4 grid (8 cells = 2³ minterms)',
        '4 variables (A, B, C, D) → 4×4 grid (16 cells = 2⁴ minterms)',
        '5+ variables → possible but harder; usually split into two 4-var maps',
      ] },
      { type: 'heading', text: 'Step 2: Label rows and columns with GRAY CODE' },
      { type: 'paragraph', text: 'This is the magic step. Gray code is an ordering where each successive value differs by exactly one bit. The standard 2-bit Gray code is 00, 01, 11, 10. Using this for rows AND columns means every adjacent pair of cells differs by exactly one variable.' },
      { type: 'table', headers: ['Variables','Row labels','Column labels'], rows: [
        ['2 (A,B)','0, 1 (A)','0, 1 (B)'],
        ['3 (A,B,C)','0, 1 (A)','00, 01, 11, 10 (BC)'],
        ['4 (A,B,C,D)','00, 01, 11, 10 (AB)','00, 01, 11, 10 (CD)'],
      ] },
      { type: 'heading', text: 'Step 3: Fill in 1s from the truth table' },
      { type: 'paragraph', text: 'For each row in the truth table where the output is 1, find the corresponding cell in the K-map (by matching the input bits) and write a 1. Leave 0s blank or write 0 — your choice.' },
      { type: 'heading', text: 'Step 4: Group the 1s (see next section)' },
      { type: 'paragraph', text: 'Once all 1s are placed, you look for rectangular groups of 1s (size 1, 2, 4, 8, or 16) and write one product term per group.' },
      { type: 'warning', text: 'The K-map WRAPS AROUND. The leftmost column is adjacent to the rightmost column. The top row is adjacent to the bottom row. So a group can span across the edges.' },
    ],
  },
  {
    id: 'kmap-pairs',
    title: 'How to Make Groups (Pairs, Quads, Octets)',
    icon: '⬚',
    blocks: [
      { type: 'heading', text: 'Group sizes must be powers of 2' },
      { type: 'paragraph', text: 'A group can only contain 1, 2, 4, 8, or 16 cells. Why? Because each doubling removes exactly one variable from the product term. A group of 1 keeps all variables; a group of 2 drops 1 variable; a group of 4 drops 2 variables; a group of 8 drops 3 variables; a group of 16 drops all variables (output is just F=1).' },
      { type: 'table', headers: ['Group size','Name','Variables dropped','Term example (4-var map)'], rows: [
        ['1','Single','0 of 4','A·B̄·C·D (full 4-var term)'],
        ['2','Pair','1 of 4','A·B̄·C (3-var term)'],
        ['4','Quad','2 of 4','A·B̄ (2-var term)'],
        ['8','Octet','3 of 4','A (1-var term)'],
        ['16','All 1s','4 of 4','1 (F = 1)'],
      ] },
      { type: 'heading', text: 'Rules for grouping' },
      { type: 'list', items: [
        '✅ Groups must be RECTANGULAR (squares are OK, also 1×2, 1×4, 2×4, etc.)',
        '✅ Group size must be a power of 2 (1, 2, 4, 8, 16)',
        '✅ Cells can wrap around the edges (left↔right, top↔bottom)',
        '✅ Cells can overlap — a cell can be in multiple groups',
        '✅ Every 1 must be in at least one group',
        '❌ Diagonal groups are NOT allowed (only horizontal/vertical rectangles)',
        '❌ Groups of 3, 5, 6, 7 are NOT allowed',
      ] },
      { type: 'heading', text: 'The strategy' },
      { type: 'list', items: [
        '1. Start with the LARGEST possible groups first (octets before quads, quads before pairs)',
        '2. Each group should be as large as possible',
        '3. Use as few groups as possible',
        '4. After picking maximal groups, every 1 must be covered by at least one group',
        '5. If a 1 is already covered, you do NOT need to add it to another group (but you can if it makes a bigger group)',
      ] },
      { type: 'tip', text: 'A "pair" (group of 2) eliminates 1 variable. A "quad" (group of 4) eliminates 2 variables. Bigger groups = simpler expressions = fewer gates. Always prefer bigger groups!' },
    ],
  },
  {
    id: 'kmap-read-term',
    title: 'How to Read the Simplified Term from a Group',
    icon: '🔍',
    blocks: [
      { type: 'paragraph', text: 'Once you have a group, you need to write the product term that the group represents. Here is the simple rule:' },
      { type: 'heading', text: 'The rule' },
      { type: 'paragraph', text: 'For each variable, look at all cells in the group. If the variable is the SAME value (0 or 1) in every cell of the group, include it in the term. If the variable CHANGES across the group, drop it.' },
      { type: 'list', items: [
        'If variable X = 1 in all cells → write X',
        'If variable X = 0 in all cells → write X̄ (X bar)',
        'If variable X is 1 in some cells and 0 in others → drop X',
      ] },
      { type: 'example', title: 'Example 1: A pair in a 4-var map', expression: 'Cells m(0) and m(1)', explanation: 'm0 = ĀB̄C̄D̄, m1 = ĀB̄C̄D. Variable D changes (0→1) so drop it. A, B, C all stay 0. Term = ĀB̄C̄.' },
      { type: 'example', title: 'Example 2: A quad in a 4-var map', expression: 'Cells m(0), m(1), m(3), m(2)', explanation: 'These are the entire top row. A=0, B=0 throughout. C and D both change. Term = ĀB̄.' },
      { type: 'example', title: 'Example 3: An octet in a 4-var map', expression: 'Cells m(0,1,3,2,4,5,7,6)', explanation: 'These are the top two rows. Only A stays constant (= 0). B, C, D all change. Term = Ā.' },
      { type: 'heading', text: 'Final answer' },
      { type: 'paragraph', text: 'After writing one product term per group, OR them all together with +. That is your simplified sum-of-products (SOP) expression.' },
    ],
  },
  {
    id: 'kmap-worked-example',
    title: 'Worked Example: 3-Variable K-map',
    icon: '🧮',
    blocks: [
      { type: 'paragraph', text: 'Problem: Simplify F(A,B,C) = Σm(1, 3, 5, 7) — that is, the truth table has 1s at minterms 1, 3, 5, 7.' },
      { type: 'heading', text: 'Step 1: Lay out the 3-var K-map' },
      { type: 'paragraph', text: 'A 3-var K-map has 2 rows (A=0, A=1) and 4 columns (BC = 00, 01, 11, 10). Minterms are placed as follows:' },
      { type: 'table', headers: ['A \\ BC','00','01','11','10'], rows: [
        ['0','m0','m1','m3','m2'],
        ['1','m4','m5','m7','m6'],
      ] },
      { type: 'heading', text: 'Step 2: Place the 1s' },
      { type: 'table', headers: ['A \\ BC','00','01','11','10'], rows: [
        ['0','0','1','1','0'],
        ['1','0','1','1','0'],
      ] },
      { type: 'heading', text: 'Step 3: Identify groups' },
      { type: 'paragraph', text: 'Look at the four 1s — they form a perfect 2×2 quad in the middle two columns. That quad covers m1, m3, m5, m7.' },
      { type: 'heading', text: 'Step 4: Read the term' },
      { type: 'list', items: [
        'A: m1, m3 have A=0; m5, m7 have A=1 → A changes → DROP A',
        'B: m1, m5 have B=0; m3, m7 have B=1 → B changes → DROP B',
        'C: m1, m3, m5, m7 all have C=1 → C stays → INCLUDE C',
      ] },
      { type: 'paragraph', text: 'The simplified term is just: C' },
      { type: 'heading', text: 'Final answer' },
      { type: 'paragraph', text: 'F = C' },
      { type: 'tip', text: 'We started with four minterms and ended with a single variable! This is the power of K-maps: visual simplification that often beats algebraic manipulation.' },
    ],
  },
  {
    id: 'kmap-dont-cares',
    title: 'Don\'t-Care Conditions (Optional)',
    icon: '❓',
    blocks: [
      { type: 'paragraph', text: 'Sometimes a circuit\'s output for certain input combinations is irrelevant — those combinations will never occur, or the output doesn\'t matter. These are called "don\'t-care" conditions and are marked with X (or d) in the K-map.' },
      { type: 'heading', text: 'How to use don\'t-cares' },
      { type: 'list', items: [
        'Treat each X as EITHER 0 or 1 — whichever gives you a bigger group',
        'You do NOT have to cover all Xs with groups (only 1s must be covered)',
        'Don\'t-cares can dramatically simplify the final expression',
      ] },
      { type: 'example', title: 'BCD example', expression: 'F = Σm(0,1,2,3,5,7,8,9) + d(10,11,12,13,14,15)', explanation: 'In BCD (binary-coded decimal), values 10-15 are invalid. Treat them as don\'t-cares. This lets you form bigger groups and get a simpler expression than if you treated them as 0s.' },
    ],
  },
];

export const BOOLEAN_FUNCTION_NOTES: NoteSection[] = [
  {
    id: 'bf-intro',
    title: 'Boolean Functions — Definition and Basics',
    icon: '🔢',
    intro: 'A boolean function is a function whose inputs and output are all boolean (0 or 1). It is described by a boolean expression using AND, OR, and NOT operations on boolean variables.',
    blocks: [
      { type: 'heading', text: 'Definition' },
      { type: 'paragraph', text: 'A boolean function of n variables is a mapping f: {0,1}ⁿ → {0,1}. It assigns a single output (0 or 1) to each possible combination of n input bits. Since there are 2ⁿ input combinations and each maps to one of 2 outputs, there are 2^(2ⁿ) possible boolean functions of n variables.' },
      { type: 'table', headers: ['n (variables)','2ⁿ (input combos)','2^(2ⁿ) (possible functions)'], rows: [
        ['1','2','4'],
        ['2','4','16'],
        ['3','8','256'],
        ['4','16','65,536'],
        ['5','32','~4 billion'],
      ] },
      { type: 'heading', text: 'Example' },
      { type: 'paragraph', text: 'F(A, B) = A·B̄ + Ā·B is a 2-variable boolean function. It evaluates to 1 when A and B differ (this is the XOR function).' },
    ],
  },
  {
    id: 'bf-representations',
    title: 'Ways to Represent a Boolean Function',
    icon: '📝',
    blocks: [
      { type: 'paragraph', text: 'A boolean function can be represented in many equivalent ways. Each form has its own use — algebra for manipulation, truth tables for completeness, circuits for implementation.' },
      { type: 'heading', text: '1. Algebraic expression' },
      { type: 'paragraph', text: 'Example: F = A·B + Ā·C. Uses variables, AND (·), OR (+), and NOT (overbar). Compact but not unique — the same function has many equivalent expressions.' },
      { type: 'heading', text: '2. Truth table' },
      { type: 'paragraph', text: 'Lists every input combination and the output. For n variables, the table has 2ⁿ rows. UNIQUE for each function — no two functions have the same truth table.' },
      { type: 'example', title: 'F = A·B + Ā·C truth table', expression: 'F(A,B,C)', explanation: 'See the table below — for each of the 8 input combinations, evaluate the expression to get the output.' },
      { type: 'table', headers: ['A','B','C','F'], rows: [
        ['0','0','0','0'],
        ['0','0','1','1'],
        ['0','1','0','0'],
        ['0','1','1','1'],
        ['1','0','0','0'],
        ['1','0','1','0'],
        ['1','1','0','1'],
        ['1','1','1','1'],
      ] },
      { type: 'heading', text: '3. Logic circuit' },
      { type: 'paragraph', text: 'A diagram of gates connected by wires. Each gate implements AND, OR, NOT, etc. The circuit is what actually gets built in hardware.' },
      { type: 'heading', text: '4. Minterm / Maxterm form' },
      { type: 'paragraph', text: 'A compact way to specify the function by listing which rows of the truth table are 1 (minterms) or 0 (maxterms). For example: F = Σm(1, 3, 6, 7) means F is 1 at minterms 1, 3, 6, 7.' },
      { type: 'heading', text: '5. Karnaugh map' },
      { type: 'paragraph', text: 'A visual representation that places truth-table rows in a Gray-code grid for easy simplification (see the K-map tab).' },
    ],
  },
  {
    id: 'bf-minterms-maxterms',
    title: 'Minterms and Maxterms',
    icon: '∑',
    blocks: [
      { type: 'heading', text: 'Minterm (product term)' },
      { type: 'paragraph', text: 'A minterm of n variables is a product (AND) term in which every variable appears exactly once, either in its normal form (X) or complemented form (X̄). For n variables there are 2ⁿ minterms.' },
      { type: 'list', items: [
        'For 2 vars (A, B): m0 = ĀB̄, m1 = ĀB, m2 = AB̄, m3 = AB',
        'For 3 vars (A, B, C): m0 = ĀB̄C̄, m1 = ĀB̄C, ..., m7 = ABC',
        'A minterm evaluates to 1 for exactly ONE input combination',
      ] },
      { type: 'heading', text: 'Sum of Minterms (canonical SOP)' },
      { type: 'paragraph', text: 'Any boolean function can be written as the OR of the minterms for which F=1. Notation: F = Σm(list of minterm numbers).' },
      { type: 'example', title: 'Example', expression: 'F(A,B,C) = Σm(1, 3, 5, 7)', explanation: 'F = ĀB̄C + ĀBC + AB̄C + ABC. (This is the same as F = C — see the K-map worked example.)' },
      { type: 'heading', text: 'Maxterm (sum term)' },
      { type: 'paragraph', text: 'A maxterm is a sum (OR) term in which every variable appears exactly once. A maxterm evaluates to 0 for exactly ONE input combination. Notation: F = ΠM(list of maxterm numbers where F=0).' },
      { type: 'tip', text: 'Memory aid: MIN-terms → MINIMUM number of 1s in the truth table row (only one 1). MAX-terms → MAXIMUM number of 1s (only one 0).' },
    ],
  },
  {
    id: 'bf-sop-pos',
    title: 'Sum-of-Products (SOP) and Product-of-Sums (POS)',
    icon: '⚙️',
    blocks: [
      { type: 'heading', text: 'Sum of Products (SOP)' },
      { type: 'paragraph', text: 'An OR of AND-terms. Example: F = A·B + B̄·C + A·C̄. Each AND-term is a "product"; the whole expression is the "sum" (OR) of products.' },
      { type: 'paragraph', text: 'SOP is the natural output of K-map simplification. It maps directly to a two-level circuit: a layer of AND gates feeding into a single OR gate.' },
      { type: 'heading', text: 'Product of Sums (POS)' },
      { type: 'paragraph', text: 'An AND of OR-terms. Example: F = (A+B)·(B̄+C)·(A+C̄). Each OR-term is a "sum"; the whole expression is the "product" (AND) of sums.' },
      { type: 'paragraph', text: 'POS is obtained by grouping the 0s in a K-map instead of the 1s.' },
      { type: 'heading', text: 'Which one to use?' },
      { type: 'list', items: [
        'Use SOP if the truth table has fewer 1s than 0s',
        'Use POS if the truth table has fewer 0s than 1s',
        'Both give correct, equivalent results; SOP is more common in teaching',
      ] },
    ],
  },
  {
    id: 'bf-simplification',
    title: 'Simplifying Boolean Functions',
    icon: '✨',
    blocks: [
      { type: 'paragraph', text: 'Why simplify? A simpler expression needs fewer gates, fewer wires, less power, and a smaller chip. There are three main methods:' },
      { type: 'heading', text: 'Method 1: Algebraic simplification' },
      { type: 'paragraph', text: 'Apply boolean laws (identity, idempotent, complement, distributive, absorption, De Morgan\'s) step by step to reduce the expression. Requires practice to spot which law to apply.' },
      { type: 'example', title: 'Example', expression: 'F = A·B + A·B·C', explanation: 'Factor A·B: F = A·B·(1 + C) = A·B·1 = A·B (using identity A+1=1, then A·1=A).' },
      { type: 'heading', text: 'Method 2: Karnaugh maps' },
      { type: 'paragraph', text: 'Visual method, best for 2-4 variables. See the K-map tab for a full tutorial. Faster than algebra and less error-prone for small functions.' },
      { type: 'heading', text: 'Method 3: Quine-McCluskey algorithm' },
      { type: 'paragraph', text: 'A tabular method that works for any number of variables. Same logic as K-maps but algorithmic — can be programmed into a computer. Used in CAD tools for circuit design.' },
      { type: 'tip', text: 'For hand calculations with 4 or fewer variables, K-maps are almost always the fastest method. For 5+ variables, switch to Quine-McCluskey or use software.' },
    ],
  },
  {
    id: 'bf-laws-recap',
    title: 'Boolean Laws Cheat Sheet (Quick Recap)',
    icon: '📋',
    blocks: [
      { type: 'paragraph', text: 'These are the algebraic laws you can use to simplify boolean expressions. They are listed in the Boolean Laws tab with full examples — here is a quick reference.' },
      { type: 'table', headers: ['Law','Identity','Result'], rows: [
        ['Identity','A + 0','A'],
        ['Identity','A · 1','A'],
        ['Null','A + 1','1'],
        ['Null','A · 0','0'],
        ['Idempotent','A + A','A'],
        ['Idempotent','A · A','A'],
        ['Complement','A + Ā','1'],
        ['Complement','A · Ā','0'],
        ['Involution','Ā̄','A'],
        ['Commutative','A + B','B + A'],
        ['Commutative','A · B','B · A'],
        ['Associative','(A+B)+C','A+(B+C)'],
        ['Associative','(A·B)·C','A·(B·C)'],
        ['Distributive','A·(B+C)','(A·B)+(A·C)'],
        ['Distributive','A+(B·C)','(A+B)·(A+C)'],
        ['Absorption','A·(A+B)','A'],
        ['Absorption','A+(A·B)','A'],
        ['De Morgan','¬(A·B)','Ā+B̄'],
        ['De Morgan','¬(A+B)','Ā·B̄'],
      ] },
    ],
  },
];
